kind: PersistentVolume
apiVersion: v1
metadata:  
  name: persistent-storage-jenkins
  labels:    
    type: local
spec:  
  storageClassName: manual  
  capacity:    
    storage: 2Gi  
  persistentVolumeReclaimPolicy: Recycle  
  accessModes:
    - ReadWriteOnce  
  hostPath:    
    path: "/root"