kind: Service
apiVersion: v1
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: jenkins
    tier: frontend
  type: LoadBalancer